name: reillo_mobprog
description: "A Facebook replication app built with Flutter."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/post/
    - assets/images/user/
    - assets/fonts/
  fonts:
    - family: Klavika
      fonts:
        - asset: assets/fonts/KlavikaBoldBold.otf
    - family: Frutiger
      fonts:
        - asset: assets/fonts/FrutigerLTStd-Roman.otf
  uses-material-design: true